### ISSUE TITLE
v4 does not work (edit) I fixed v4! 

### ISSUE THREAD

**Issue by stewpidtnlvr** [lrq3000/javascript-racer#1]
when I click on v4, the race starts but after about a half-second in, it freezes

**Comment by stewpidtnlvr** [comment]
@lrq3000  you have to copy the code from the original game for "common.js" and "stats.js". make two new files called "v4common.js", and "v4stats.js". link those two files instead of the common.js and stats.js file that you made. Then, delete the link to "racer.js", delete what you wrote in the "script" element, copy the javascript code from the original game v4, and paste it into the script....and viola! here are some screenshots: 
![image](https://user-images.githubusercontent.com/61797693/99430384-e0833000-28ce-11eb-8ca8-5562882861cf.png)
![image](https://user-images.githubusercontent.com/61797693/99430461-fbee3b00-28ce-11eb-84a2-0d8872bbf0d8.png)
I can send you the source code if you would like it. If you want it.....just one thing. You are gonna have to change the fps back to 60fps because I changed it so that it goes 200mph on my version.

**Comment by lrq3000** [comment]
Oh you're right! Thank you very much for reporting this issue!

Actually that's a regression, normally it should work out of the box, and it did in the past. I'm not sure why v4 is not working anymore. If you copy from the old project, you likely won't get all the features I have added such as random track generation.

**Comment by lrq3000** [comment]
This is now fixed, it was caused by a missing check for turbo_left hud html element access, please try again the latest release (you can try directly on the website: https://lrq3000.github.io/javascript-racer/v4.final.html ) and make sure to clear your browser's cache before (or use incognito mode) so that the javascript is forcefully reloaded.

Thank you for reporting this issue!
